use_frameworks!

target 'CertificateSigningRequestSwift_Example' do
  pod 'CertificateSigningRequestSwift', :path => '../'

  target 'CertificateSigningRequestSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
