use_frameworks!
platform :ios, '10.0'
target 'CertificateSigningRequest_Example' do
  pod 'CertificateSigningRequest', :path => '../'

  target 'CertificateSigningRequest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
