use_frameworks!
platform :ios, '10.0'
#platform :macos, '10.12'
target 'CertificateSigningRequest_Example' do
  pod 'CertificateSigningRequest', :path => '../'

  target 'CertificateSigningRequest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
