coverage:
  ignore:
    - Tests/.*
    - TestHost/.*
  status:
    patch: true
      default:
        target: 80
    changes: false
    project:
      default:
        target: 90
comment:
  require_changes: false
