coverage:
  ignore:
    - Tests/.*
    - TestHost/.*
    - TestHostTests/.*
    - TestHostTV/.*
    - TestHostTVTests/.*
  status:
    patch: true
    changes: false
    project:
      default:
        target: 83
comment:
  require_changes: true
