name: release

on:
  push:
    tags: '*'
    
jobs:
  cocoapods:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Deploy CocoaPods
        run: set -o pipefail && env NSUnbufferedIO=YES pod trunk push CertificateSigningRequest.podspec --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
